disabled = false
weight = 1
title = "Nebulo"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "m"
secondaryLogo = "j"

[params.author]
name = "Nebulo"
email = "nebulo@pm.me"
image = "747.png"
imageQuality = ""
headline = "A place bring for noobies, if you dont know where to start"
bio = ""
